#ifndef DEVICE_PROFILE_H_
#define DEVICE_PROFILE_H_

#define DEVICE_PRODUCT_NAME "IotKit"
#define DEVICE_PORTAL_AP_IP "192.168.4.1"
#define DEVICE_PORTAL_NETMASK "255.255.255.0"
#define DEVICE_PORTAL_HOSTNAME "iot-kit"
#define DEVICE_PORTAL_FQDN DEVICE_PORTAL_HOSTNAME ".local"
#define DEVICE_API_PORT 8080
#define DEVICE_WIFI_PROFILE_VERSION "1.0"

#define PROVISION_STA_CONNECT_TIMEOUT_MS 30000
#define PROVISION_STA_RECONNECT_DELAY_MS 15000
#define PROVISION_BOOT_FALLBACK_AP_DELAY_MS 15000
#define PROVISION_AP_STOP_SETTLE_MS 200
#define PROVISION_STA_START_AFTER_RESPONSE_MS 1500

#endif /* DEVICE_PROFILE_H_ */
